### ISSUE TITLE
JWT Malformed di /user-rent/

### ISSUE THREAD

**Issue by khw315** [Rent-O-Dicoding-Cycle-5/BackEnd-Development#12]
Bang, di endpoint /user-rent/ masih JWT malformed. Saya mo integrasi user history.

![image](https://github.com/Rent-O-Dicoding-Cycle-5/BackEnd-Development/assets/64533786/bd0c2187-7540-474d-adb4-49bef5a03e63)

**Comment by DaffaHabibullah** [comment]
Halo bang Faisal,

Base URL API itu untuk Development, silahkan diganti dengan Base URL Production.
Terimakasih
